# Practice problems

Complete the questions below.

* [Variables and Arithmetic Operators](#variables)
* [Boolean data and Conditionals](#boolean)
* [Lists, loops, and NumPy arrays](#lists)
* [Functions](#functions)
* [Challenge questions](#challenge-questions)

### Variables and Arithmetic Operators <a class="anchor" id="variables"></a>

**1. Set the variable `my_name` to your name and then print it.**

In [ ]:
my_name = "Alex"

print(my_name)

SyntaxError: ignored

**2. Now, use string interpolation to add your name to a string that says, "My name is YOURNAME" â€“ here, YOURNAME should be replaced with the value saved to `my_name`.**

In [1]:
my_name_string = "Alex"

print(f"My name is {my_name_string}")

My name is Alex

**4. Multiply `x` and `y`, save them to a variable called `z` and print the result. The results should be 250.**

In [2]:
x = 10
y = 25

print(x * y)

250

**5. Use the variables `x`, `y`, and `z` (set below) and mathematical operators (`+`, `-`, `*`, and `/`) that results in the value `10`. Set this to the `result` variable and then print it.**

In [3]:
x = 4
y = 5
z = 11

print(z + x - y)

10

**6. Adjust the code below so it prints 15**

In [4]:
x = 5
y = 10

z = 5 + 10

print(z)

15

**7. Fix the code below so it prints, "I just learned Python"**

In [5]:
my_variable = "I just learned Python"

print(my_variable)

I just learned Python

**8. Use `x`, `y`, and `z` and arithmetic operators to set `result` to 20. Do not change any of the variables values.**

In [8]:
x = 4
y = 22
z = 6

result = y + x - z

print(result)

20

**9. Change the `__` to an arithmetic operator so the following code prints `2`**

In [9]:
x = 5 - 3

print(x)

2

**10. Change the `__` to an arithmetic operator so the code prints 22.**

In [10]:
x = 11 * 2

print(x)

22

### Boolean data and Conditionals <a class="anchor" id="boolean"></a>

**1. Set x to a value that will make the following code print "Success!"**

In [11]:
x = 6

if x > 5:
    print("Success!")

Success!

**2. Set x to a value that will make the following code print "Inside the else!"**

In [13]:
x = 4

if x != 4:
    print("Inside the if!")
else:
    print("Inside the else!")

Inside the else!

**3. Set `x` to a value and add a boolean expression to the `if` block of this `if-elif-else` block so the code will print, "Inside the elif!"**

In [14]:
x = 4

if x > 5:
    print("Inside the if")
elif x < 5:
    print('Inside the elif!')
else:
    print("Inside")

Inside the elif!

**4. Replace the blank (`__`) in the block below so the following code prints, "Inside the if!"**

In [15]:
x = 8

if x > 6:
    print("Inside the if!")
else:
    print("Inside the else!")

Inside the if!

**5. Write a conditional statement that prints "Positive" if the variable `x` is set to a value greater than `0`.**

In [17]:
x = 5

if x > 0:
  print("Positive")

Positive

**6. Write an `if-else` statement that prints "Positive" if the variable `x` is set to a value greater than 0, and prints "Negative" if the variable `x` is set to a value less than 0.**

In [ ]:
x = 5

if x > 0:
  print("Positive")
if x < 0:
  print("Negative")

**7. Write an `if-elif-else` statement that prints:**
- "Positive" if the variable `x` is set to a value greater than 0
- "Negative" if the variable `x` is set to a value less than 0.
- "Equal to zero" if the variable `x` is set to zero.

In [18]:
x = 5

if x > 0:
  print("Positive")
elif x < 0:
  print("Negative")
else:
  print("Equal to zero")

Positive

### Lists, loops, and NumPy arrays <a class="anchor" id="lists"></a>

**1. Use a for loop to print every value in the `my_list` variable.**

In [19]:
my_list = [1, 2, 3, 4, 5]

for val in my_list:
  print(val)

1
2
3
4
5

**2. Create a list of strings, and then use a for loop to print its contents. The result should be:**

```
These
are
the
items
of
the
list
```

In [20]:
my_list = ["These", "are", "the", "items", "of", "the", "list"]

for my_str in my_list:
  print(my_str)

These
are
the
items
of
the
list

**3. Use slice notation to print `[0, 1, 2]` from the list below**

In [21]:
my_list = [0, 1, 2, 3, 4, 5]

print(my_list[:3])

[0, 1, 2]

**4. Use `range()` to create a list from `0` to `50` and save it to `my_list`. Print the result.**

In [22]:
my_list = list(range(0, 51))

print(my_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]

**5. Append 15 to `my_list`**

In [23]:
my_list = [0, 3, 6, 9, 12]

# Append here
my_list.append(15)

print(my_list)

[0, 3, 6, 9, 12, 15]

**6. Fix the `for` loop so it prints:**

Hi<br>
Hello<br>
How are you?

In [24]:
my_list = ["Hi", "Hello", "How are you?"]

for my_str in my_list:
    print(my_str)

Hi
Hello
How are you?

**7. Fill in the blanks below so the code prints:**

0<br>
1<br>
2

In [27]:
my_list = [0, 1, 2, 3, 4, 5]
i = 0

while my_list[i] < 3:
    print(i)
    i += 1

0
1
2

**8. Import NumPy**

In [28]:
import numpy as np

**9. Create a NumPy array with `0`, `10`, and `100` and save it to a variable called `my_array`**

In [30]:
my_array = np.array([0, 10, 100])

**10. Use NumPy to calculate the mean and sum of `my_array`. Print the results.**

In [31]:
my_array.mean()

36.666666666666664

### Functions <a class="anchor" id="functions"></a>

**1. Call the function below. It will print, "You called the function!"**

In [33]:
def my_function():
    print("You called the function!")

# Call the function below:
my_function()

You called the function!

**2. Call the `print_my_name()` function. Pass your name into the function as an argument.**

In [34]:
def print_my_name(name):
    print(f"My name is, {name}")

# Call the function below:
print_my_name("Alex")

My name is, Alex

**3. Define a function that accepts 2 values and prints the sum. Call the function once you have defined it.**

In [35]:
def my_func(val_1, val_2):
  print(val_1 + val_2)

my_func(2, 4)

6

**4. Fix the function below so it accepts a name as an argument and returns the string, "Hello, Alex".**

In [37]:
def return_greeting(input_name):
    input_name
    return "Hello, " + input_name


greeting = return_greeting("Alex")
print(greeting)

Hello, Alex

**5. Define a function in python that accepts 3 values and returns the maximum of three numbers.**

In [40]:
def find_max(val_1, val_2, val_3):
  return np.max([val_1, val_2, val_3])

print(find_max(7, 4, 5))

7

**6. Define a function that accepts a number and returns "Negative" if the value is less than zero, and "Not negative" if the number is not less than zero.**

In [42]:
def my_func(val):
  if val < 0:
    print("Negative")
  else:
    print("Not negative")

my_func(-4)

Negative

**7. Define a function that accepts radius and returns the area of a circle.**

In [43]:
def get_circle_area(radius):
  return 3.14 * radius ** 2

get_circle_area(2)

12.56